float64 field_length
float64 field_width
float64 goal_width
float64 goal_depth
float64 field_arcs_radius

float64 ball_speed
float64 ball_slope
float64 ball_intercept
float64 robot_speed
float64 robot_angular_velocity

int32 boundary_width
FieldLineSegment[] field_lines
FieldCircularArc[] field_arcs

geometry_msgs/Pose2D goal_plus
geometry_msgs/Pose2D goal_minus
geometry_msgs/Pose2D goal_plus_half
geometry_msgs/Pose2D goal_minus_half
